id: 167
title: "Two Sum II - Input Array Is Sorted"
difficulty: "Medium"
url: "https://leetcode.com/problems/two-sum-ii---input-array-is-sorted/"
tags: []
attempts:
  - date: "2025-12-27"
    status: "red"
    notes: |
      Conditioner: sorted array, target.
      Key Insight: two pointer.
  - date: "2025-12-30"
    status: "yellow"  # Attempt 2
    notes: "finish but need use print to debug, need to see constraints more carefully."
