id: 271
title: "Encode and Decode Strings"
difficulty: "Medium"
url: "https://leetcode.com/problems/encode-and-decode-strings/"
tags: []
attempts:
  - date: "2025-12-22"
    status: "red"
    notes: ""
  - date: "2026-01-01"
    status: "red"  # Attempt 2
    notes: "know to use delmiter and length prefix for encode, but having trouble implementing decode"
