id: 271
title: "Encode and Decode Strings"
difficulty: "Medium"
url: "https://leetcode.com/problems/encode-and-decode-strings/"
tags: []
attempts:
  - date: "2025-12-22"
    status: "red"
    notes: ""
