id: 36
title: "Valid Sudoku"
difficulty: "Medium"
url: "https://leetcode.com/problems/valid-sudoku/"
tags: []
attempts:
  - date: "2025-12-25"
    status: "red"
    notes: "Use hash sets to track seen numbers in rows, columns, and squares"
  - date: "2026-01-06"
    status: "red"  # Attempt 2
    notes: "Use collections.defaultdict(set) to create each row, column, and 3x3 square hash sets."
  - date: "2026-01-21"
    status: "red"  # Attempt 3
    notes: "collections.defaultdict(set), first check then update the value in hash set"
