id: 347
title: "Top K Frequent Elements"
difficulty: "Medium"
url: "https://leetcode.com/problems/top-k-frequent-elements/"
tags: []
attempts:
  - date: "2025-12-20"
    status: "red"
    notes: ""
  - date: "2025-12-27"
    status: "red"  # Attempt 2
    notes: |
      Blocker: Could not figure out how to use bucket sort.
      Key Insight: Frequent elements means we can use a hash map, then use bucket sort to group by frequency.
      Method: hash
  - date: "2026-01-11"
    status: "red"  # Attempt 3
    notes: | 
      Know to use bucket sort and hash map, but dont know how to implement.
      Blocker: Implementation of bucket sort and hash map.
      Key Insight: Frequent elements -> We can use a hash map to count. then we can use bucket sort to group elements by frequency.
      Method: hash, bucket sort
